config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get 'delivery_lookup', to: 'deliveries#lookup'
  resources :shipping_modes, only: [:index, :new, :create, :show, :edit, :update] do
    post 'deactivate', on: :member
    resources 'delivery_times', only: [:create, :index, :edit, :update] do 
      post 'disable', on: :collection
    end
    resources 'distance_based_fees', only: [ :create, :index, :edit, :update] do
      post 'disable', on: :collection
    end
    resources 'weight_based_fees', only: [ :create, :index, :edit, :update] do
      post 'disable', on: :collection
    end
    
  end
  resources :vehicles, only: [:index, :new, :create, :show, :edit, :update] do
    resources :vehicle_shipping_modes, only: [:new, :create, :destroy]
    get 'search', on: :collection
  
  end

  resources :service_orders, only: [:index, :new, :create, :show] do 
    get 'closed', on: :collection
    post 'initialize_delivery_of', on: :member
    post 'close_delivery_of', on: :member
    resources :delay_reasons, only: [:new, :create]
  end
  
  

end

app/models/distance_based_fee.rb
class DistanceBasedFee < ApplicationRecord
  belongs_to :shipping_mode
  validate :check_if_intervals_intersect
  validates :min_distance, :max_distance, :fee, presence: true
  validates :min_distance, comparison: { greater_than_or_equal_to: 0 }
  validates :fee, comparison: { greater_than: 0 }
  validates :max_distance, comparison: { greater_than: :min_distance }
  
  def check_if_intervals_intersect
    sm = self.shipping_mode
    sm.distance_based_fees.reload.each do |dbf|  
      if dbf.min_distance <= self.max_distance && self.min_distance <= dbf.max_distance && dbf != self 
        self.errors.add(:min_distance, 'pode estar em outro intervalo')
        self.errors.add(:max_distance, 'pode estar em outro intervalo')
      end

    end
  end
end

app/controllers/distance_based_fees_controller.rb
class DistanceBasedFeesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :create, :edit, :update]
  before_action :check_user_role, only: [:create, :edit]
  def index
    @shipping_mode = ShippingMode.find(params[:shipping_mode_id])
    @shipping_mode_distance_based_fee = DistanceBasedFee.new
    @distance_based_fees = @shipping_mode.distance_based_fees.reload
  end

  def create
    @shipping_mode = ShippingMode.find(params[:shipping_mode_id])
    shipping_mode_distance_based_fee_params = params.require(:distance_based_fee).permit(:min_distance,
                                                                                 :max_distance, :fee)
    @shipping_mode_distance_based_fee = @shipping_mode.distance_based_fees.new(shipping_mode_distance_based_fee_params)
    if @shipping_mode_distance_based_fee.save
      redirect_to shipping_mode_distance_based_fees_path(@shipping_mode.id), notice: 'Nova configuração de preço salva com sucesso'
    else 
      @distance_based_fees = @shipping_mode.distance_based_fees.reload
      flash.now[:alert] = "Configuração não pode ser salva"
      render :index
    end
  end

  def edit
    @shipping_mode = ShippingMode.find(params[:shipping_mode_id])
    @shipping_mode_distance_based_fee = DistanceBasedFee.find(params[:id])
    @distance_based_fees = @shipping_mode.distance_based_fees.reload

  end

  def update
    @shipping_mode = ShippingMode.find(params[:shipping_mode_id])
    @shipping_mode_distance_based_fee = DistanceBasedFee.find(params[:id])
    
    shipping_mode_distance_based_fee_params = params.require(:distance_based_fee).permit(:min_distance,
                                                                                  :max_distance, :fee)
    if @shipping_mode_distance_based_fee.update(shipping_mode_distance_based_fee_params)
      redirect_to shipping_mode_distance_based_fees_path(@shipping_mode.id), notice: 'Taxa atualizada com sucesso'
    else 
      @distance_based_fees = @shipping_mode.distance_based_fees.reload
      flash.now[:alert] = "Taxa não pode ser atualizada"
      render :edit
    end

  end

  def disable
    @shipping_mode = ShippingMode.find(params[:shipping_mode_id])
    @shipping_mode.distance_based_fees.destroy_all
    redirect_to shipping_mode_distance_based_fees_path(@shipping_mode.id)

  end

end

app/views/distance_based_fees/_form.html.erb
<%= form_with(model: [@shipping_mode, @shipping_mode_distance_based_fee]) do |f| %>
  <div>
  <%= f.label :min_distance %>
  <%= f.number_field :min_distance %>
  </div>
  <div>
  <%= f.label :max_distance %>
  <%= f.number_field :max_distance %>
  </div>
  <div>
  <%= f.label :fee %>
  <%= f.number_field :fee, step: 0.01 %>
  </div>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/distance_based_fees/edit.html.erb
<h2>Editar configuração de preços de acordo com distância</h2>
<% if @shipping_mode_distance_based_fee.errors.any? %>
  <div>
    <ul>
      <% @shipping_mode_distance_based_fee.errors.each do |e| %>
        <li><%= e.full_message %></li>
      <% end %>
    </ul>
    
  </div>
<% end %>
<div>
  <table>
    <thead>
      <tr>
        <th><%= DistanceBasedFee.human_attribute_name(:min_distance) %> (km)</th>
        <th><%= DistanceBasedFee.human_attribute_name(:max_distance) %> (km)</th>
        <th><%= DistanceBasedFee.human_attribute_name(:fee) %> (R$)</th>
      <tr>
    </thead>
    <% @distance_based_fees.each do |dbf| %>
      <% if dbf == @shipping_mode_distance_based_fee %>
        <%= form_with(model: [@shipping_mode, @shipping_mode_distance_based_fee]) do |f| %>
          <tr>
            <td><%= dbf.min_distance %></td>
            <td><%= dbf.max_distance %></td>
            <td><%= f.label :fee, class: "hide_label" %> <%= f.number_field :fee, step: 0.01 %></td>
            <td><%= f.submit 'Atualizar' %></td>
          </tr>
        <% end %>
      <% else %>
        <tr>
            <td><%= dbf.min_distance %></td>
            <td><%= dbf.max_distance %></td>
            <td><%= dbf.fee %></td>
 
          </tr>
      <% end %>
    <% end %>
  
  </table>
  
</div>

<%= link_to "Voltar", shipping_mode_distance_based_fees_path(@shipping_mode.id) %>

app/views/distance_based_fees/index.html.erb
<h2>Taxas de serviço de acordo com distância para modalidade <%= @shipping_mode.name %></h2>
<%= link_to "Voltar", shipping_mode_path(@shipping_mode.id) %>
<div>
  <table>
    <thead>
      <tr>
        <th><%= DistanceBasedFee.human_attribute_name(:min_distance) %> (km)</th>
        <th><%= DistanceBasedFee.human_attribute_name(:max_distance) %> (km)</th>
        <th><%= DistanceBasedFee.human_attribute_name(:fee) %> (R$)</th>
      <tr>
    </thead>
    <% @distance_based_fees.each do |dbf| %>
      <tr>
        <td><%= dbf.min_distance %></td>
        <td><%= dbf.max_distance %></td>
        <td><%= number_to_currency(dbf.fee, unit: "") %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Editar', edit_shipping_mode_distance_based_fee_path(@shipping_mode.id, dbf.id) %></td>
        <% end %>
      </tr>
    <% end %>
  
  </table>
  
</div>

<% if user_signed_in? && current_user.admin? %>
  <h3>Cadastro de novas configurações</h3>
  <%= button_to 'Deletar configuração', disable_shipping_mode_distance_based_fees_path(@shipping_mode.id) %>
  <%= render 'form' %>
<% end %>