config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get 'delivery_lookup', to: 'deliveries#lookup'
  resources :shipping_modes, only: [:index, :new, :create, :show, :edit, :update] do
    post 'deactivate', on: :member
    resources 'delivery_times', only: [:create, :index, :edit, :update] do 
      post 'disable', on: :collection
    end
    resources 'distance_based_fees', only: [ :create, :index, :edit, :update] do
      post 'disable', on: :collection
    end
    resources 'weight_based_fees', only: [ :create, :index, :edit, :update] do
      post 'disable', on: :collection
    end
    
  end
  resources :vehicles, only: [:index, :new, :create, :show, :edit, :update] do
    resources :vehicle_shipping_modes, only: [:new, :create, :destroy]
    get 'search', on: :collection
  
  end

  resources :service_orders, only: [:index, :new, :create, :show] do 
    get 'closed', on: :collection
    post 'initialize_delivery_of', on: :member
    post 'close_delivery_of', on: :member
    resources :delay_reasons, only: [:new, :create]
  end
  
  

end

app/models/shipping_mode.rb
class ShippingMode < ApplicationRecord

  has_many :delivery_times
  has_many :distance_based_fees
  has_many :weight_based_fees
  has_many :vehicle_shipping_modes
  has_many :vehicles, through: :vehicle_shipping_modes
  has_many :delivery_data
  has_many :service_orders, through: :delivery_data
  enum status: {active: 10, inactive: 20}

  validates :name, :min_distance, :max_distance, :min_weight, :max_weight, :fixed_fee, presence: true
  validates :min_distance, :min_weight, :fixed_fee, comparison: { greater_than_or_equal_to: 0 }
  validates :min_distance, comparison: { less_than: :max_distance }
  validates :max_distance, comparison: { greater_than: :min_distance }

  validates :min_weight, comparison: { less_than: :max_weight }
  validates :max_weight, comparison: { greater_than: :min_weight }
  validates :fixed_fee, comparison: { greater_than: 0 }
  validates :name, uniqueness: true
  

  def find_estimated_delivery_time(distance: )
    sm_delivery_time = self.delivery_times.where(min_distance: ..distance).find_by(max_distance: distance..)
    sm_delivery_time.estimated_delivery_time
  end

  def find_weight_based_fee(product_weight: )
    sm_weight_based_fee = self.weight_based_fees.where(min_weight: ..product_weight).find_by(max_weight: product_weight..)
    sm_weight_based_fee.fee_per_km
  end

  def find_distance_based_fee(distance: )
    sm_distance_based_fee = self.distance_based_fees.where(min_distance: ..distance).find_by(max_distance: distance..)
    sm_distance_based_fee.fee
  end

  def total_price(distance:, product_weight:)
    find_distance_based_fee(distance: distance ) + find_weight_based_fee(product_weight: product_weight )*distance + self.fixed_fee
  end


end

app/controllers/shipping_modes_controller.rb
class ShippingModesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :deactivate]
  before_action :check_user_role, only: [:new, :create, :edit, :update, :deactivate]
  def index
    @shipping_modes = ShippingMode.all
  end

  def show
    @shipping_mode = ShippingMode.find(params[:id])
  end
  
  def new
    @shipping_mode = ShippingMode.new
  end

  def create
    
    sm_params = params.require(:shipping_mode).permit(:name, :min_distance, :max_distance, 
                                                      :min_weight, :max_weight, :description,
                                                      :fixed_fee)
    @shipping_mode = ShippingMode.new(sm_params)
    if @shipping_mode.save
      redirect_to shipping_mode_path(@shipping_mode.id), notice: "Modalidade de transporte salva com sucesso"
    else
      flash.now[:alert] = "Cadastro de modalidade de transporte não pode ser realizada"
      render :new
    end

  end

  def edit
    @shipping_mode = ShippingMode.find(params[:id])
  end

  def update
    @shipping_mode = ShippingMode.find(params[:id])
    sm_params = params.require(:shipping_mode).permit(:name, :min_distance, :max_distance, 
                                                      :min_weight, :max_weight, :description,
                                                      :fixed_fee, :status)
    if @shipping_mode.update(sm_params)
      redirect_to @shipping_mode, notice: 'Modalidade de transporte atualizada com sucesso'
    else
      flash.now[:alert] = "Modalidade de transporte não pode ser atualizada"
      render :edit
    end
  end

  def deactivate
    @shipping_mode = ShippingMode.find(params[:id])
    @shipping_mode.inactive!

    redirect_to shipping_modes_path, notice: 'Modalidade de transporte desativada com sucesso'

  end
  
  private

  def shipping_mode_params
  end

  
  
end

app/views/shipping_modes/_form.html.erb
<% if @shipping_mode.errors.any? %>
  <div>
    <ul>
      <% @shipping_mode.errors.each do |e| %>
        <li><%= e.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div>
<%= form_with(model: @shipping_mode) do |f| %>
  <div class="mb-3 row">
    <%= f.label :name, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="mb-3 row">
    <%= f.label :max_distance, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.number_field :max_distance, class: "form-control" %>
    </div>
  </div>
  <div class="mb-3 row">
    <%= f.label :min_distance, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.number_field :min_distance, class: "form-control" %>
    </div>
  </div>
  <div class="mb-3 row">
    <%= f.label :max_weight, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.number_field :max_weight, class: "form-control" %>
    </div>
  </div>
  <div class="mb-3 row">
    <%= f.label :min_weight, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.number_field :min_weight, class: "form-control" %>
    </div>
  </div>
  <div class="mb-3 row">
    <%= f.label :fixed_fee, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      R$<%= f.number_field :fixed_fee, step: 0.01, class: "form-control" %>
    </div>
  </div>
  <div class="mb-3 row">
    <%= f.label :description, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  


  <%= f.submit 'Enviar' %>
<% end %>
</div>

app/views/shipping_modes/edit.html.erb
<h2>Editar modalidade de transporte</h2> 
<%= button_to 'Desativar', deactivate_shipping_mode_path(@shipping_mode.id) %>


<%= render 'form' %>

app/views/shipping_modes/index.html.erb
<h2 class= "display-8 text-center">Modalidades de transporte</h2>
<br/>
<% if user_signed_in?  && current_user.admin? %>
 <%= link_to 'Cadastrar nova modalidade de transporte', new_shipping_mode_path, class: "btn btn-dark m-2" %>
<% end %>
<div class="card-group p-3">
<% @shipping_modes.active.each do |sm| %>
  <div class="card p-3">
  <h4><%= link_to sm.name, shipping_mode_path(sm.id), class: "card-title text-black-50" %></h4>
  <dl class="row">
    <dt class="col-sm-5">Intervalo de distância:</dt>
    <dd class="col-md-auto"><%= sm.min_distance %>-<%= sm.max_distance %> km</dd>
    <dt class="col-sm-5">Intervalo de peso:</dt>
    <dd class="col-md-auto"><%= number_with_precision(sm.min_weight.to_f/1000) %>-<%= number_with_precision(sm.max_weight.to_f/1000, precision: 0 ) %> kg</dd>
    <dt class="col-sm-5"><%= ShippingMode.human_attribute_name(:fixed_fee) %>:</dt>
    <dd class="col-md-auto"><%= number_to_currency(sm.fixed_fee) %></dd>
  
  </dl>
  </div>
<% end %>
</div>
<% if @shipping_modes.empty? %>
  Não há modalidades de transporte disponíveis
<% end %>

app/views/shipping_modes/new.html.erb
<h3 class="text-center">Cadastrar nova modalidade de transporte</h3>

<%= render "form" %>

app/views/shipping_modes/show.html.erb
<h3 class="text-center">
    <%= @shipping_mode.name %>
    <% if user_signed_in? && current_user.admin? %>
        <small class="text-muted fs-6"><%= link_to 'Editar', edit_shipping_mode_path(@shipping_mode.id) %></small>
    <% end %>
</h3>
<ul class="nav justify-content-center my-2">
    <li class="nav-item"><%= link_to 'Prazos', shipping_mode_delivery_times_path(@shipping_mode.id), class: "nav-link" %></li>
    <li class="nav-item"><%= link_to 'Taxas de acordo com distância', shipping_mode_distance_based_fees_path(@shipping_mode.id), class: "nav-link" %></li>
    <li class="nav-item"><%= link_to 'Taxas de acordo com peso', shipping_mode_weight_based_fees_path(@shipping_mode.id), class: "nav-link" %></li>

</ul>


<div class="card">
    <div class="card-body m-2">
    <p class="lead"><%= @shipping_mode.description %></p>
    <dl class="row">
        <dt class="col-sm-8">Intervalo de distância de serviço:</dt>
        <dd class="col-sm-4"><%= @shipping_mode.min_distance %>-<%= @shipping_mode.max_distance %> km</dd>
        <dt class="col-sm-8">Intervalo de peso de serviço:</dt>
        <dd class="col-sm-4"><%= number_with_precision(@shipping_mode.min_weight.to_f/1000) %>-<%= number_with_precision(@shipping_mode.max_weight.to_f/1000, precision: 0) %> kg</dd>
        <dt class="col-sm-8"><%= ShippingMode.human_attribute_name(:fixed_fee) %>:</dt>
        <dd class="col-sm-4"><%= number_to_currency(@shipping_mode.fixed_fee) %></dd>
        <dt class="col-sm-8">Status:</dt>
        <dd class="col-sm-4"><%= t(@shipping_mode.status) %></dd>  
    </dl>
    </div>
</div>