config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get 'delivery_lookup', to: 'deliveries#lookup'
  resources :shipping_modes, only: [:index, :new, :create, :show, :edit, :update] do
    post 'deactivate', on: :member
    resources 'delivery_times', only: [:create, :index, :edit, :update] do 
      post 'disable', on: :collection
    end
    resources 'distance_based_fees', only: [ :create, :index, :edit, :update] do
      post 'disable', on: :collection
    end
    resources 'weight_based_fees', only: [ :create, :index, :edit, :update] do
      post 'disable', on: :collection
    end
    
  end
  resources :vehicles, only: [:index, :new, :create, :show, :edit, :update] do
    resources :vehicle_shipping_modes, only: [:new, :create, :destroy]
    get 'search', on: :collection
  
  end

  resources :service_orders, only: [:index, :new, :create, :show] do 
    get 'closed', on: :collection
    post 'initialize_delivery_of', on: :member
    post 'close_delivery_of', on: :member
    resources :delay_reasons, only: [:new, :create]
  end
  
  

end

app/models/service_order.rb
class ServiceOrder < ApplicationRecord
  has_one :delivery_datum
  has_one :shipping_mode, through: :delivery_datum
  has_one :closed_delivery_datum
  has_one :delay_reason, through: :closed_delivery_datum
  has_many :full_addresses
  accepts_nested_attributes_for :full_addresses

  enum status: {pending: 4, initialized: 6, closed: 9}

  before_validation :generate_code, on: :create
  
  validates :product_code, :recipient_name, :recipient_registration_number, :distance, presence: true
  validates :distance, comparison: { greater_than: 0 }
  validates :full_addresses, length: { is: 2 }
  validates_associated :full_addresses
  
  validate :check_if_one_recipient_one_shipper


  def late?
    if !self.pending?
      if Time.now > self.delivery_datum.end_date
        return true
      else
        return false
      end
    end
  end

  def find_available_shipping_modes
    distance = self.distance
    product_weight = self.product_weight
    ShippingMode.where(min_distance: ..distance).where(max_distance: distance..).where(min_weight: ..product_weight).where(max_weight: product_weight..)
  end

  def build_delivery_data(shipping_mode:)
    vehicle = shipping_mode.vehicles.operational.first
    estimated_delivery_time = shipping_mode.find_estimated_delivery_time(
                                        distance: self.distance)
    total_price = shipping_mode.total_price(distance: self.distance,
                               product_weight: self.product_weight )
    DeliveryDatum.new(service_order: self, shipping_mode: shipping_mode, vehicle: vehicle, 
                      estimated_delivery_time: estimated_delivery_time,
                      total_price: total_price,
                      creation_date: Time.now, end_date: Time.now + estimated_delivery_time.hours)

  end

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(15).upcase
  end

 

  def check_if_one_recipient_one_shipper
    if self.full_addresses.first.recipient? && self.full_addresses.last.recipient?
      self.errors.add :base, :invalid, message: "Ordem de serviço deve ter destinatário e recipiente"
    elsif self.full_addresses.first.shipper? && self.full_addresses.last.shipper?
      self.errors.add :base, :invalid, message: "Ordem de serviço deve ter destinatário e recipiente"

    end
  end

end

app/controllers/service_orders_controller.rb
class ServiceOrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user_role, only: [:new, :create]

  def show
    @service_order = ServiceOrder.find(params[:id])
    @shipping_modes = @service_order.find_available_shipping_modes
    @delivery_datum = DeliveryDatum.new

  end

  def index
    @service_orders = ServiceOrder.all
  end

  def new
    @service_order = ServiceOrder.new

    @service_order.full_addresses.build()

  end

  def create
    service_order_params = params.require(:service_order).permit(:product_code, :product_width,
                           :product_height, :product_depth, :product_weight,
                           :recipient_name, :recipient_registration_number, :distance,
                           full_addresses_attributes: [:id, :belonging_to, :city, :state, :zip_code, :address])
    @service_order = ServiceOrder.new(service_order_params)
    if @service_order.save
      redirect_to service_order_path(@service_order.id), notice: 'Ordem de serviço criada com sucesso'
    else

      @service_order.full_addresses.build()
      flash.now[:alert] = 'Ordem de serviço não pode ser criada'
      render :new
    end



  end

  def initialize_delivery_of
    @shipping_mode = ShippingMode.find(params[:delivery_datum][:shipping_mode_id])
    @service_order = ServiceOrder.find(params[:id])
    @delivery_datum = @service_order.build_delivery_data(shipping_mode: @shipping_mode)
    if @delivery_datum.save

      redirect_to @service_order, notice: "Ordem de serviço iniciada com sucesso" 
    
    end
  end

  def close_delivery_of
    @service_order = ServiceOrder.find(params[:id])
    delivery_datum = @service_order.delivery_datum
    closed_delivery_datum = @service_order.create_closed_delivery_datum(closing_date: Time.now, delivery_datum: delivery_datum)
    if closed_delivery_datum.late?
      redirect_to new_service_order_delay_reason_path(@service_order.id), notice: "Ordem de serviço terminada com atraso"
    else
      redirect_to @service_order, notice: "Ordem de serviço terminada no prazo"
    end
  end

  def closed
    @service_orders = ServiceOrder.closed
  end


  private



end

app/views/service_orders/closed.html.erb
<h2>Ordens de serviço finalizadas</h2>

<div id="closed">
  <table>
    <thead>
      <tr>
        <th>Entregas finalizadas</th>
      </tr>
      <tr>
        <th>Código da ordem de serviço</th>
        <th>Saída</th>
        <th>Destino</th>
        <th>Status</th>
      </tr>
    
    </thead>
    <tbody>
      <% @service_orders.each do |so| %>
      <tr>
        <td><%= link_to so.code, service_order_path(so.id) %></td>
        <td><%= so.full_addresses.shipper.first.city %> - <%= so.full_addresses.shipper.first.state %></td>
        <td><%= so.full_addresses.recipient.first.city %> - <%= so.full_addresses.recipient.first.state %></td>
        <td><%= t(so.status) %></td>
      </tr>
    
      <% end %>
    </tbody>  
  
  </table>


</div>

app/views/service_orders/index.html.erb
<h2>Ordens de serviço</h2>
<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'Adicionar ordem de serviço', new_service_order_path %>
<% end %>
<br/>
<br/>
<%= link_to 'Ordens de serviço finalizadas', closed_service_orders_path %>
<br/>
<br/>
<div id="pending">
  <table>
    <thead>
      <tr>
        <th>Entregas pendentes</th>
      </tr>
      <tr>
        <th>Código da ordem de serviço</th>
        <th>Saída</th>
        <th>Destino</th>
        <th>Status</th>
      </tr>
    
    </thead>
    <tbody>
      <% @service_orders.pending.each do |so| %>
      <tr>
        <td><%= link_to so.code, service_order_path(so.id) %></td>
        <td><%= so.full_addresses.shipper.first.city %> - <%= so.full_addresses.shipper.first.state %></td>
        <td><%= so.full_addresses.recipient.first.city %> - <%= so.full_addresses.recipient.first.state %></td>
        <td><%= t(so.status) %></td>
      </tr>
    
      <% end %>
    </tbody>  
  
  </table>


</div>

<br/>
<br/>

<div id="initialized">
  <table>
    <thead>
      <tr>
        <th>Entregas em andamento</th>
      </tr>
      <tr>
        <th>Código da ordem de serviço</th>
        <th>Saída</th>
        <th>Destino</th>
        <th>Status</th>
      </tr>
    
    </thead>
    <tbody>
      <% @service_orders.initialized.each do |so| %>
      <tr>
        <td><%= link_to so.code, service_order_path(so.id) %></td>
        <td><%= so.full_addresses.shipper.first.city %> - <%= so.full_addresses.shipper.first.state %></td>
        <td><%= so.full_addresses.recipient.first.city %> - <%= so.full_addresses.recipient.first.state %></td>
        <td><%= t(so.status) %></td>
      </tr>
    
      <% end %>
    </tbody>  
  
  </table>


</div>

<br/>
<br/>

app/views/service_orders/new.html.erb
<h2>Criar ordem de serviço</h2>


<%= form_with(model: @service_order) do |f| %>
  <div class="product">
  <h3>Dados do produto</h3>
    <div>
    <%= f.label :product_code %>
    <%= f.text_field :product_code %>
    </div>
    <div>
    <%= f.label :product_width %>
    <%= f.number_field :product_width %> cm
    </div>
    <div>
    <%= f.label :product_height %>
    <%= f.number_field :product_height %> cm
    </div>
    <div>
    <%= f.label :product_depth %>
    <%= f.number_field :product_depth %> cm 
    </div>
    <div>
    <%= f.label :product_weight %>
    <%= f.number_field :product_weight %> g
    </div>
  </div>
  <div class="shipper">
  <h3>Dados de retirada</h3>
    <%= f.fields_for :full_addresses do |af| %>
      <%= af.hidden_field :belonging_to, value: "shipper" %>
      <div>
      <%= af.label :city %>
      <%= af.text_field :city %>
      </div>
      <div>
      <%= af.label :state %>
      <%= af.text_field :state %>
      </div>
      <div>
      <%= af.label :address %>
      <%= af.text_field :address %>
      </div>
      <div>
      <%= af.label :zip_code %>
      <%= af.text_field :zip_code %>
      </div>

    <% end %>
  
  </div>
  <div class="recipient">
    <h3>Dados de destinatário</h3>
    
    <div>
    <%= f.label :recipient_name %>
    <%= f.text_field :recipient_name %>
    </div>
    <div>
    <%= f.label :recipient_registration_number %>
    <%= f.text_field :recipient_registration_number %>
    </div>
    <%= f.fields_for :full_addresses do |af| %>
      <%= af.hidden_field :belonging_to, value: "recipient" %>
      <div>
      <%= af.label :city %>
      <%= af.text_field :city %>
      </div>
      <div>
      <%= af.label :state %>
      <%= af.text_field :state %>
      </div>
      <div>
      <%= af.label :address %>
      <%= af.text_field :address %>
      </div>
      <div>
      <%= af.label :zip_code %>
      <%= af.text_field :zip_code %>
      </div>

    <% end %>
    <div>
    <%= f.label :distance %>
    <%= f.text_field :distance %> km
    </div>



  </div>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/service_orders/show.html.erb
<h2><%= ServiceOrder.model_name.human %> de código <%= @service_order.code %></h2>



<h4>Dados do produto</h4>
<dl>
  <dt><%= ServiceOrder.human_attribute_name(:product_code) %>:</dt>
  <dd><%= @service_order.product_code %></dd>
  <dt>Dimensões: </dt>
  <dd><%= @service_order.product_width %>cm x <%= @service_order.product_height %>cm x <%= @service_order.product_depth %>cm</dd>
  <dt><%= ServiceOrder.human_attribute_name(:product_weight) %>:</dt>
  <dd><%= @service_order.product_weight %> g</dd>
</dl>

<h4>Endereço de retirada</h4>
<dl>
  <dt><%= FullAddress.human_attribute_name(:address) %></dt>
  <dd><%= @service_order.full_addresses.shipper.first.address %></dd>
  <dt><%= FullAddress.human_attribute_name(:city) %></dt>
  <dd><%= @service_order.full_addresses.shipper.first.city %></dd>
  <dt><%= FullAddress.human_attribute_name(:state) %></dt>
  <dd><%= @service_order.full_addresses.shipper.first.state %></dd>
  <dt><%= FullAddress.human_attribute_name(:zip_code) %></dt>
  <dd><%= @service_order.full_addresses.shipper.first.zip_code %></dd>
  
</dl>

<h4>Dados do destinatário</h4>
<dl>
  <dt><%= ServiceOrder.human_attribute_name(:recipient_name) %>:</dt>
  <dd><%= @service_order.recipient_name %></dd>
  <dt><%= ServiceOrder.human_attribute_name(:recipient_registration_number) %>:</dt>
  <dd><%= @service_order.recipient_registration_number %></dd>
  <dt><%= FullAddress.human_attribute_name(:address) %></dt>
  <dd><%= @service_order.full_addresses.recipient.first.address %></dd>
  <dt><%= FullAddress.human_attribute_name(:city) %></dt>
  <dd><%= @service_order.full_addresses.recipient.first.city %></dd>
  <dt><%= FullAddress.human_attribute_name(:state) %></dt>
  <dd><%= @service_order.full_addresses.recipient.first.state %></dd>
  <dt><%= FullAddress.human_attribute_name(:zip_code) %></dt>
  <dd><%= @service_order.full_addresses.recipient.first.zip_code %></dd>
  <dt><%= ServiceOrder.human_attribute_name(:distance) %>:</dt>
  <dd><%= @service_order.distance %></dd>
 

  
</dl>

<%= t(@service_order.status) %>
<div>
  <h3>Modalidades de transporte disponíveis</h3>
  <% @shipping_modes.each do |asm| %>
    
    <b><%= asm.name %></b>
    <% if asm.delivery_times.any? && asm.distance_based_fees.any? && asm.weight_based_fees.any? %>
      <dl>
        <dt><%= ShippingMode.human_attribute_name(:fixed_fee) %>:</dt>
        <dd><%= number_to_currency(asm.fixed_fee) %></dd>
        <dt><%= DeliveryTime.human_attribute_name(:estimated_delivery_time) %>:</dt>
        <dd><%= asm.find_estimated_delivery_time(distance: @service_order.distance) %> horas</dd>
        <dt>Preço total:</dt>
        <% total_price = asm.total_price(distance: @service_order.distance, product_weight: @service_order.product_weight) %>
        <dd><%= number_to_currency(total_price) %> </dd>
      <dl>
    <% end %>
    
  <% end %>

</div>


<% if @service_order.pending? %>
  <div class="initialize">
  <h3>Inicializar entrega</h3>
  <%= form_with(model: @delivery_datum, url: initialize_delivery_of_service_order_path(@service_order.id), method: :post) do |f| %>
    <%= f.label :shipping_mode_id %>
    <%= f.collection_select :shipping_mode_id, @shipping_modes, :id, :name %>
    <%= f.submit "Iniciar" %>
  <% end %>
  </div>
<% end %>


<div>
<% if @service_order.initialized? %>
<h2>Dados da entrega</h2>
   <%= @late %>
  <dl>
    <dt>Modalidade de transporte:</dt>
    <dd><%= @service_order.delivery_datum.shipping_mode.name %></dd>
    <dt>Prazo estimado:</dt>
    <dd><%= @service_order.delivery_datum.estimated_delivery_time %> horas</dd>
    <dt>Preço total:</dt>
    <dd><%= number_to_currency(@service_order.delivery_datum.total_price) %></dd>
    <dt>Placa do veículo:</dt>
    <dd><%= @service_order.delivery_datum.vehicle.plate_number %></dd>
    <dt>Data de entrega:</dt>
    <dd><%= l(@service_order.delivery_datum.end_date.to_date) %></dd>

  </dl>
  <%= button_to "Fechar", close_delivery_of_service_order_path(@service_order.id), method: :post %>
  
<% end %>
</div>


<% if @service_order.closed? %>
<h2>Dados da entrega</h2>

  <dl>
    <dt>Modalidade de transporte:</dt>
    <dd><%= @service_order.delivery_datum.shipping_mode.name %></dd>
    <dt>Prazo estimado:</dt>
    <dd><%= @service_order.delivery_datum.estimated_delivery_time %> horas</dd>
    <dt>Preço total:</dt>
    <dd><%= number_to_currency(@service_order.delivery_datum.total_price) %></dd>
    <dt>Placa do veículo:</dt>
    <dd><%= @service_order.delivery_datum.vehicle.plate_number %></dd>
    <dt>Data de entrega estimada:</dt>
    <dd><%= l(@service_order.delivery_datum.end_date.to_date) %></dd>
    <dt>Data de fechamento de ordem de serviço:</dt>
    <dd><%= l(@service_order.closed_delivery_datum.closing_date.to_date) %></dd>
    <dt>Status:</dt>
    <dd><%= t(@service_order.closed_delivery_datum.status) %></dd>

    <% if @service_order.closed_delivery_datum.late? %>
      <dt>Motivo do atraso:</dt>
      <dd><%= @service_order.delay_reason.reason_for_delay %></dd>

    <% end %>


  </dl>
  
<% end %>
</div>