config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get 'delivery_lookup', to: 'deliveries#lookup'
  resources :shipping_modes, only: [:index, :new, :create, :show, :edit, :update] do
    post 'deactivate', on: :member
    resources 'delivery_times', only: [:create, :index, :edit, :update] do 
      post 'disable', on: :collection
    end
    resources 'distance_based_fees', only: [ :create, :index, :edit, :update] do
      post 'disable', on: :collection
    end
    resources 'weight_based_fees', only: [ :create, :index, :edit, :update] do
      post 'disable', on: :collection
    end
    
  end
  resources :vehicles, only: [:index, :new, :create, :show, :edit, :update] do
    resources :vehicle_shipping_modes, only: [:new, :create, :destroy]
    get 'search', on: :collection
  
  end

  resources :service_orders, only: [:index, :new, :create, :show] do 
    get 'closed', on: :collection
    post 'initialize_delivery_of', on: :member
    post 'close_delivery_of', on: :member
    resources :delay_reasons, only: [:new, :create]
  end
  
  

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_many :delivery_data
  has_many :service_orders, through: :delivery_data
  has_many :vehicle_shipping_modes
  has_many :shipping_modes, through: :vehicle_shipping_modes
  
  validates :plate_number, :brand, :model, :year, :max_capacity, presence: true
  validates :year, comparison: { greater_than: 1980 }
  validates :year, comparison: { less_than_or_equal_to: Date.today.year }
  validates :plate_number, format: { with: /\A[a-zA-Z]{3}[0-9]{4}\z|\A[a-zA-Z]{3}[0-9][a-zA-Z][0-9]{2}\z/}
  validates :plate_number, uniqueness: true
  enum activity: { operational: 5, maintenance: 9, busy: 11}


end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :index]
  before_action :check_user_role, only: [:new, :create, :edit, :update]
  def index
    @vehicles =  Vehicle.all
    
  end

  def show
    @vehicle = Vehicle.find(params[:id])
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    vehicle_params = params.require(:vehicle).permit(:plate_number, :model, :brand,
                                                     :year, :max_capacity, :activity)
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      redirect_to @vehicle, notice: 'Veículo salvo com sucesso'
    else
      flash.now[:notice] = 'Veículo não pode ser salvo'
      render :new

    end

  end

  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  def update
    @vehicle = Vehicle.find(params[:id])
    vehicle_params = params.require(:vehicle).permit(:plate_number, :model, :brand,
                                                    :year, :max_capacity, :activity)
    if @vehicle.update(vehicle_params)
      redirect_to @vehicle, notice: 'Veículo atualizado com sucesso'
    else
      flash.now[:notice] = 'Veículo não pode ser atualizado'
      render :edit

    end
  end

  def search
    @query = params[:query]
    @vehicles = Vehicle.where("plate_number LIKE ?", "%#{@query}%")
  end
  


end

app/views/vehicles/_form.html.erb
<% if @vehicle.errors.any? %>
  <div>
    <ul>
      <% @vehicle.errors.each do |e| %>
        <li><%= e.full_message %></li>
      <% end %>
    </ul>
    
  </div>
<% end %>

<%= form_with(model: @vehicle) do |f| %>
  <div>
    <%= f.label :plate_number %>
    <%= f.text_field :plate_number %>
  </div>
  <div>
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>
  <div>
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>
  <div>
    <%= f.label :year %>
    <%= f.number_field :year, in: 1990..Date.today.year  %>
  </div>
  <div>
    <%= f.label :max_capacity %>
    <%= f.number_field :max_capacity %> kg
  </div>
  <div> 
    <%= f.radio_button :activity, "operational" %>
    <%= f.label :operational, "Em operação" %>
    <%= f.radio_button :activity, "maintenance" %>
    <%= f.label :maintenance, "Em manutenção" %>

  </div>

  <%= f.submit 'Enviar' %>
  




<% end %>

app/views/vehicles/edit.html.erb
<h2>Editar veículo <%= @vehicle.plate_number.upcase %></h2>

<%= render 'form' %>

app/views/vehicles/index.html.erb
<h2>Veículos</h2>

<%= form_with(url: search_vehicles_url, method: :get) do |f| %>
  <div>
    <%= f.label :query, 'Consulta de veículos' %>
    <%= f.text_field :query %>
    <%= f.submit 'Buscar' %>
  
  </div>
<% end %>
<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'Adicionar veículo', new_vehicle_path %>
<% end %>

<div>
  <table>
    <thead>
      <tr><h4>Veículos operacionais</h4></tr>
      <tr>
        <th>Placa</th>
        <th>Status</th>
        <th>Modelo</th>
        <th>Marca</th>
        <th>Ano</th>
      </tr>
       
    </thead>
    <tbody>
      
      <% @vehicles.operational.each do |ov| %>
        <tr>
          <td><%= link_to ov.plate_number.upcase, vehicle_path(ov.id) %></td>
          <td><%= t(ov.activity) %></td>
          <td><%= ov.model %></td>
          <td><%= ov.brand %></td>
          <td><%= ov.year %></td>
        </tr>
      <% end %>
     
    
    </tbody>
    

</div>

<div>
  <table>
    <thead>
      <tr><h4>Veículos em manutenção</h4></tr>
      <tr>
        <th>Placa</th>
        <th>Status</th>
        <th>Modelo</th>
        <th>Marca</th>
        <th>Ano</th>
      </tr>
       
    </thead>
    <tbody>
      
      <% @vehicles.maintenance.each do |ov| %>
        <tr>
          <td><%= link_to ov.plate_number.upcase, vehicle_path(ov.id) %></td>
          <td><%= t(ov.activity) %></td>
          <td><%= ov.model %></td>
          <td><%= ov.brand %></td>
          <td><%= ov.year %></td>
        </tr>
      <% end %>
     
    
    </tbody>
    

</div>

app/views/vehicles/new.html.erb
<h2>Adicionar veículo</h2>
<% if @vehicle.errors.any? %>
  <div>
    <ul>
      <% @vehicle.errors.each do |e| %>
        <li><%= e.full_message %></li>
      <% end %>
    </ul>
    
  </div>
<% end %>

<%= form_with(model: @vehicle) do |f| %>
  <div>
    <%= f.label :plate_number %>
    <%= f.text_field :plate_number %>
  </div>
  <div>
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>
  <div>
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>
  <div>
    <%= f.label :year %>
    <%= f.number_field :year, in: 1990..Date.today.year  %>
  </div>
  <div>
    <%= f.label :max_capacity %>
    <%= f.number_field :max_capacity %>
  </div>
  <div> 
    <%= f.radio_button :activity, "operational" %>
    <%= f.label :operational, "Em operação" %>
    <%= f.radio_button :activity, "maintenance" %>
    <%= f.label :maintenance, "Em manutenção" %>

  </div>

  <%= f.submit 'Enviar' %>
  

<% end %>

app/views/vehicles/search.html.erb
<h2>Resultados da pesquisa: <%= @query %></h2>

<%= @vehicles.count %> <%= Vehicle.model_name.human(count: @vehicles.count).downcase %> <%= t(:found, count: @vehicles.count) %>
<div>
<% @vehicles.each do |v| %>
  <dl>
    <dt><%= Vehicle.human_attribute_name(:plate_number) %>:</dt>
    <dd><%= link_to v.plate_number.upcase, vehicle_path(v.id) %></dd>
    <dt><%= Vehicle.human_attribute_name(:model) %>:</dt>
    <dd><%= v.model %></dd>
    <dt><%= Vehicle.human_attribute_name(:brand) %>:</dt>
    <dd><%= v.brand %></dd>
    <dt><%= Vehicle.human_attribute_name(:year) %>:</dt>
    <dd><%= v.year %></dd>
    <dt>Status: </dt>
    <dd><%= t(v.activity) %></dd>
  
  
  </dl>
<% end %>
</div>

app/views/vehicles/show.html.erb
<h2>Veículo de placa <%= @vehicle.plate_number.upcase %></h2>
<%= link_to 'Editar', edit_vehicle_path(@vehicle.id) %>
<div>
  <dl>
    <dt><%= Vehicle.human_attribute_name(:model) %>:</dt>
    <dd><%= @vehicle.model %></dd>
    <dt><%= Vehicle.human_attribute_name(:brand) %>:</dt>
    <dd><%= @vehicle.brand %></dd>
    <dt><%= Vehicle.human_attribute_name(:year) %>:</dt>
    <dd><%= @vehicle.year %></dd>
    <dt><%= Vehicle.human_attribute_name(:max_capacity) %>:</dt>
    <dd><%= @vehicle.max_capacity %> kg</dd>
    <dt>Status: </dt>
    <dd><%= t(@vehicle.activity) %></dd>



  </dl>
</div>


<h3>Modalidades de transporte disponíveis para veículo</h3>
<% if @vehicle.shipping_modes.any? %>
  <ul>
    <% @vehicle.shipping_modes.each do |sm| %>
      <% vsm = VehicleShippingMode.find_by(vehicle_id: @vehicle.id, shipping_mode_id: sm.id) %>
      <% if user_signed_in? && current_user.admin? %>
        <li><%= sm.name %> | <%= button_to 'Desabilitar', vehicle_vehicle_shipping_mode_path(@vehicle.id, vsm.id), method: :delete %></li>
      <% end %>
    <% end %>
  </ul>
<% end %>
<%= link_to 'Habilitar para modalidade de transporte', new_vehicle_vehicle_shipping_mode_path(vehicle_id: @vehicle.id) %>